TSK-1400: H2 in server mode for rest spring example
Taskana/taskana pull request #1284
Opened 2020-09-28 12:21 UTC by gitgoodjhe

2020-09-28 14:35 UTC, holgerhagen requested changes

2020-09-28 14:35 UTC, holgerhagen commented on rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/rest/ExampleRestConfiguration.java
> +  @Bean(initMethod = "start", destroyMethod = "stop")
maybe we should make a note that this is only required to let the adapter example connect to the same database? 

And I would you another port as 9090. this is still a rather common port for web applications.

2020-10-14 06:49 UTC, mustaphazorgati commented on rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/rest/ExampleRestConfiguration.java
> +        "-tcp", "-tcpAllowOthers", "-tcpPort", "9095");
should we make this port configurable in our application.properties?

2020-10-15 10:42 UTC, mustaphazorgati approved these changes

2020-10-15 11:46 UTC, merged