TSK-1401: Update Typeahead component with material design
Taskana/taskana pull request #1312
Opened 2020-10-22 08:45 UTC by Franzi321

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2020-10-26 08:34 UTC, cnguyen-de commented on web/src/app/shared/components/type-ahead/type-ahead.component.html
> +  <label class="typeahead__label">
```suggestion
```

  Remove this label

2020-10-26 08:34 UTC, cnguyen-de commented on web/src/app/shared/components/type-ahead/type-ahead.component.html
> +      <mat-label>{{placeHolderMessage}}</mat-label>
```suggestion
      <mat-label>{{dataSource.selected?.name ? dataSource.selected?.name : placeHolderMessage}}</mat-label>
```

and change this mat-label would result this:
<img width="228" alt="Screenshot 2020-10-26 at 09 28 41" src="https://user-images.githubusercontent.com/6671583/97149887-a5795b00-176d-11eb-90e1-f1b80d88fdd6.png">
<img width="219" alt="Screenshot 2020-10-26 at 09 31 26" src="https://user-images.githubusercontent.com/6671583/97150161-06a12e80-176e-11eb-90bc-b886fe4e3803.png">

2020-10-26 08:34 UTC, cnguyen-de commented on web/src/app/shared/components/type-ahead/type-ahead.component.ts
> +  _value = '';
unused variable

2020-10-26 08:34 UTC, cnguyen-de commented on web/src/app/shared/components/type-ahead/type-ahead.component.ts
> +  private input;
ditto

2020-10-26 08:42 UTC, sofie29 requested changes

2020-10-26 08:42 UTC, sofie29 commented on web/src/app/shared/components/type-ahead/type-ahead.component.html
> +    <mat-form-field class="typeahead__form" focused="false" appearance="outline">
I get a warning that says "Attribute focused is not allowed here". Please remove in case it is not necessary.

2020-10-26 08:42 UTC, sofie29 commented on web/src/app/shared/components/type-ahead/type-ahead.component.html
> +        [matAutocomplete]="auto" placeholder="{{placeHolderMessage}}" [(ngModel)]="value" name="acessId"
attribute name should be 'accessId', not 'acessId

2020-10-26 08:42 UTC, sofie29 commented on web/src/app/shared/components/type-ahead/type-ahead.component.ts
> +  constructor(private accessIdsService: AccessIdsService, private el: ElementRef) {}
Is 'el' used?

2020-10-26 08:42 UTC, sofie29 commented on web/src/app/shared/components/type-ahead/type-ahead.component.spec.ts
> +  it('should create', () => {
I think the name 'should create component' would be more appropriate.

2020-10-26 08:42 UTC, sofie29 commented on web/src/app/shared/components/type-ahead/type-ahead.component.spec.ts
> +      let input = fixture.debugElement.query(By.css('.typeahead__form-input'));
A variable 'debugElement' was created in line 51. This variable should replace 'fixture.debugElement'.

2020-10-26 08:42 UTC, sofie29 commented on web/src/app/shared/components/type-ahead/type-ahead.component.ts
> +  }
Why don't you call initializeDataSource() instead of changeValue()? I think changeValue() is unnecessary.

2020-10-26 08:42 UTC, sofie29 commented on web/src/app/shared/components/type-ahead/type-ahead.component.scss
> +  //color: $invalid;
Please remove the comment in case it is not necessary.

2020-10-28 08:33 UTC, cnguyen-de approved these changes

2020-10-28 08:43 UTC, merged