TSK-1416: Truncation of Instant Membervariables
Taskana/taskana pull request #1313
Opened 2020-10-22 13:12 UTC by tge20

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2020-10-22 13:36 UTC, gitgoodjhe requested changes

2020-10-22 13:36 UTC, gitgoodjhe commented on lib/taskana-core/src/main/java/pro/taskana/classification/internal/models/ClassificationImpl.java
> +    return created != null ? created.truncatedTo(ChronoUnit.MICROS) : null;
All Instants in other entities are truncated to MILLIS, I think this should be changed in this class too

2020-10-26 09:39 UTC, tge20 commented
https://sonarcloud.io/dashboard?id=tge20_taskana

2020-10-27 11:53 UTC, gitgoodjhe approved these changes

2020-10-28 16:59 UTC, merged