TSK-1476: Rework workbasket access items
Taskana/taskana pull request #1360
Opened 2020-12-03 15:41 UTC by Franzi321

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2020-12-07 09:17 UTC, sofie29 requested changes

2020-12-07 09:17 UTC, sofie29 commented on web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
> +						</td>
I think this ticket https://taskana.atlassian.net/browse/TSK-1044 should be part of the rework of the workbasket access items. We can also work on this ticket in a separate PR.

2020-12-09 14:09 UTC, Franzi321 commented on web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.scss
> +::ng-deep .myForm .mat-form-field-wrapper {
The selector is actually valid, webstorm apparently doesn't want to know it :D I've read that several people get the same error message. But I can try to handle it without the ng-deep selector.

2020-12-18 13:26 UTC, cnguyen-de approved these changes

2020-12-18 13:37 UTC, cnguyen-de commented
👏🏻

2020-12-18 14:27 UTC, merged