TSK-1362: Fixed the test data to not include invalid owners for Workbaskets
Taskana/taskana pull request #1379
Opened 2020-12-16 15:54 UTC by tge20

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2020-12-16 15:56 UTC, tge20 commented
https://sonarcloud.io/dashboard?branch=TSK-1362&id=tge20_taskana

2020-12-16 16:03 UTC, tge20 commented
@gitgoodjhe, @holgerhagen, @mustaphazorgati 
Could I talk to (one of) you about some details concerning this task when you have time / are back? Isn't urgent...

2020-12-21 03:34 UTC, mustaphazorgati requested changes

2020-12-21 03:34 UTC, mustaphazorgati commented on common/taskana-common-data/src/main/resources/sql/sample-data/workbasket.sql
>  -- WORKBASKET TABLE           (ID                                        , KEY          , CREATED              , MODIFIED             , NAME                       , DOMAIN    , TYPE      , DESCRIPTIO
Please add/remove spaces so that after your changes all lines are aligned to this header.

2020-12-21 03:34 UTC, mustaphazorgati commented on common/taskana-common-data/src/main/resources/sql/test-data/workbasket.sql
>  -- KSC workbaskets
Please add/remove spaces so that after your changes all lines are aligned to this header.

2020-12-21 03:34 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketAccTest.java
> -            .ownerLike("%an%", "%te%")
Do you know why we wrap the string with `%`? This is not necessary.

2020-12-21 03:34 UTC, mustaphazorgati commented
You have a code smell -> please fix that

2021-01-05 13:39 UTC, mustaphazorgati approved these changes

2021-01-05 14:27 UTC, merged