TSK-1486: Deleted unnecessary UnitTests of taskana-core
Taskana/taskana pull request #1383
Opened 2020-12-18 10:21 UTC by tge20

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2020-12-18 14:33 UTC, tge20 commented
https://sonarcloud.io/dashboard?branch=TSK-1486&id=tge20_taskana

2020-12-21 03:37 UTC, mustaphazorgati commented
Let's walk through this together later

2021-01-26 12:09 UTC, mustaphazorgati requested changes

2021-01-26 12:09 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/CreateTaskAccTest.java
> -  @WithAccessId(user = "user-1-1")
why did you remove this?

2021-01-26 12:09 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/QueryTaskWithAttachmentAccTest.java
>      assertThat(attachmentSummaries).isEmpty();
please make this a seperate test again.

2021-01-26 12:09 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/QueryTaskWithAttachmentAccTest.java
> +  void should_ReturnTaskSummaryIncludingAttachmentsIfPresent_When_UsingTaskQuery() {
please rework this name (after test separation)

2021-01-26 12:09 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/QueryTaskWithAttachmentAccTest.java
> -  void should_ConfirmIfAttachmentSummariesAreCorrect() throws Exception {
why did you delete this?

2021-01-26 12:09 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/QueryTaskWithAttachmentAccTest.java
> -    assertThat(tasks).hasSize(1);
`taskService.createTaskQuery().idIn("TKI:00...00").list()`

2021-01-26 12:09 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
> -  void testQueryTaskByCustomAttributes() throws Exception {
Why did you remove this?

2021-01-26 12:09 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/pro/taskana/sampledata/SampleDataGeneratorTest.java
> -package pro.taskana.sampledata;
Please move this test to `taskana-common-data`

2021-02-26 10:38 UTC, mustaphazorgati requested changes

2021-02-26 10:38 UTC, mustaphazorgati commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
> +      Workbasket oldWorkbasket, WorkbasketImpl workbasketImplToUpdate) throws ConcurrencyException {
why is this public?

2021-02-26 10:38 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/pro/taskana/classification/internal/models/ClassificationModelsCloneTest.java
> -package pro.taskana.classification.internal.models;
This test is important.

2021-02-26 10:38 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/pro/taskana/monitor/internal/ReportTest.java
> -class ReportTest {
This is important.

2021-02-26 10:38 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/pro/taskana/monitor/internal/WorkingDaysToDaysReportConverterTest.java
> -class WorkingDaysToDaysReportConverterTest {
This is important

2021-02-26 10:38 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskAttachmentTest.java
> -class TaskAttachmentTest {
this is important.

2021-02-26 11:14 UTC, mustaphazorgati submitted a review, later dismissed

2021-02-26 11:18 UTC, mustaphazorgati submitted a review, later dismissed

2021-02-26 11:23 UTC, mustaphazorgati approved these changes

2021-02-26 16:59 UTC, mustaphazorgati approved these changes

2021-02-26 17:01 UTC, merged