TSK-1499: Fixed bug of also cleaning completed tasks with parentProcessId null/empty
Taskana/taskana pull request #1394
Opened 2021-01-08 17:25 UTC by tge20

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-01-11 08:48 UTC, tge20 commented
https://sonarcloud.io/project/issues?branch=TSK-1499&id=tge20_taskana&resolved=false&types=CODE_SMELL

2021-01-26 19:17 UTC, tge20 commented
https://sonarcloud.io/dashboard?branch=TSK-1499&id=tge20_taskana

2021-01-28 09:05 UTC, mustaphazorgati requested changes

2021-01-28 09:05 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/test/java/acceptance/jobs/HistoryCleanupJobAccTest.java
> +  void should_CleanTaskHistoryEventsWithParentProcessIdEmpty_When_TaskCompleted() throws Exception {
This is exactly the same test as above. Please refactor this and use a dynamic test. For examples just search for `@TestFactory`

2021-01-28 09:05 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
> +  }
This test is a duplicate to the test above. Please use dynamic tests to increase maintainability.

2021-01-28 09:05 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
> +    assertThat(tasksAfterCleaning.get(0).getId()).isEqualTo(taskId2);
```suggestion
    assertThat(tasksAfterCleaning).extracting(TaskSummary::getId).containsExactly(taskId2);
```

2021-01-28 13:12 UTC, tge20 commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/jobs/HistoryCleanupJob.java
> +            filterSameParentBusinessHistoryEventsQualifiedToClean(historyEventCandidatesToClean));
First I add all the events with parentBusinessProcessId NULL or EMPTY, than I check the other events for uncompleted events with the same parentProcess and add those, where none are existing.
But I observed a possible bug: The NULL events should be kicked out from the historyEventCandidatesToClean List such that they may not be added a second time. I will fix it.

2021-02-02 20:30 UTC, mustaphazorgati approved these changes

2021-02-03 08:34 UTC, merged