TSK-1494: Validate the AccessIds with EqualsFilter instead of Whitesp…
Taskana/taskana pull request #1397
Opened 2021-01-14 16:23 UTC by gitgoodjhe

…aceWildcardsFilter

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-01-14 16:23 UTC, gitgoodjhe commented
https://sonarcloud.io/dashboard?branch=TSK-1494&id=gitgoodjhe_taskana

2021-01-14 16:47 UTC, holgerhagen requested changes

2021-01-14 16:47 UTC, holgerhagen commented on rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
> +      return !accessIds.isEmpty();
Don't we miss the uniqueness check here? I was expecting a check on count equals 1.

2021-01-14 16:47 UTC, holgerhagen commented on rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
> +  public boolean validateAccessId(final String name) {
I think we should either add some debugging here to understand why the validation fails, or we should throw an Exception with the reason stated in the message.

2021-01-15 08:54 UTC, holgerhagen approved these changes

2021-01-15 08:57 UTC, merged