TSK-1544: Throw error for unknown query parameter
Taskana/taskana pull request #1503
Opened 2021-02-23 17:15 UTC by gitgoodjhe

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-02-23 17:15 UTC, gitgoodjhe commented
https://sonarcloud.io/dashboard?branch=TSK-1544&id=gitgoodjhe_taskana

2021-02-23 23:44 UTC, mustaphazorgati requested changes

2021-02-23 23:44 UTC, mustaphazorgati commented on history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/simplehistory/rest/TaskHistoryEventControllerIntTest.java
> +          new ParameterizedTypeReference<TaskHistoryEventRepresentationModel>() {};
Dang! I don't like this Syntax. We have to talk about this in our cop. 
This is just a reminder for me to add the entry.

2021-02-23 23:44 UTC, mustaphazorgati commented on history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/simplehistory/rest/TaskHistoryEventControllerIntTest.java
> +  void should_ThrowException_When_ProvidingInvalidFilterParams() {
This is a duplicate. Please check `should_ReturnBadStatusErrorCode_When_InvalidQueryParameterIsUsed`

2021-02-23 23:44 UTC, mustaphazorgati commented on rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
> +  @Test
This is a duplicate. Please check `testThrowsExceptionIfInvalidFilterIsUsed`

2021-02-23 23:44 UTC, mustaphazorgati commented on rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
> +  void should_ThrowException_When_ProvidingInvalidFilterParams() {
This is a duplicate. Please check `testThrowsExceptionIfInvalidFilterIsUsed`

2021-02-23 23:44 UTC, mustaphazorgati commented on rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketControllerIntTest.java
> +  void should_ThrowException_When_ProvidingInvalidFilterParams() {
This is a duplicate. Please check `testThrowsExceptionIfInvalidFilterIsUsed`

2021-02-24 09:51 UTC, mustaphazorgati approved these changes

2021-02-24 10:09 UTC, merged