Tsk 1647
Taskana/taskana pull request #1626
Opened 2021-07-05 07:03 UTC by mustaphazorgati

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-07-05 11:35 UTC, cnguyen-de requested changes

2021-07-05 11:35 UTC, cnguyen-de commented on web/src/app/workplace/components/task-master/task-master.component.ts
> +              this.notificationsService.showInformation('EMPTY_WORKBASKET');
warning would be more appropriate

2021-07-06 07:53 UTC, cnguyen-de commented on web/src/app/workplace/components/task-master/task-master.component.ts
> +              this.notificationsService.showInformation('EMPTY_WORKBASKET');
also deleting task results no notification popup, there should be one

2021-07-06 07:57 UTC, sofie29 commented on web/src/app/shared/services/notifications/notification.service.ts
> +  showError(errorKey: string, messageVariables: object = {}) {
I think we don't declare a variable which is of type ToastOptions. `messageVariables `are inserted into the message, for example the workbasketId.

2021-07-06 09:58 UTC, sofie29 requested changes

2021-07-06 09:58 UTC, sofie29 commented on common/taskana-common/src/main/java/pro/taskana/common/api/exceptions/WrongCustomHolidayFormatException.java
> +                + "i.e. 01.05 for the first of may.",
Capital letter: "May"

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/classification/api/exceptions/ClassificationInUseException.java
> +                + "attachments associated with the classification.",
Capital letters: Classification, Tasks, Attachments

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/classification/api/exceptions/ClassificationInUseException.java
>  /** Thrown if a specific task is not in the database. */
Capital letter: "Task"

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/classification/api/exceptions/ClassificationNotFoundException.java
>  /** Thrown if a specific task is not in the database. */
missing @linkplain

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/classification/api/exceptions/ClassificationNotFoundException.java
> +        String.format("The classification '%s' wasn't found", classificationId),
Capital letter "Classification"

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
> +                "The classification '%s' has the same key and parentKey",
Capital letter "Classification"

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
> +   * @throws InvalidArgumentException if the given classification has no key, the type is not valid
missing `@linkplain`

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/common/api/TaskanaEngine.java
> +   * Set the connection to be used by taskana in mode {@linkplain
TASKANA

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/task/api/exceptions/InvalidCallbackStateException.java
> +    this.expectedCallbackState = requiredCallbackStates;
I would prefer the same name for both variables like `requiredCallbackStates`

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/task/api/exceptions/InvalidOwnerException.java
>  public class InvalidOwnerException extends TaskanaException {
missing private fields and getter methods

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/task/api/exceptions/InvalidStateException.java
>  /** This exception is thrown when the task state doesn't allow the requested operation. */
missing `@linkplain`

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/NotAuthorizedToQueryWorkbasketException.java
>  /** This exception is used to communicate that a user is not authorized to query a Workbasket. */
missing `@linkplain`

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/WorkbasketAccessItemAlreadyExistException.java
>  public class WorkbasketAccessItemAlreadyExistException extends TaskanaException {
missing private attributes and getters

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/WorkbasketAlreadyExistException.java
>  /** Thrown, when a workbasket does already exits, but wanted to create with same ID. */
missing `@linkplain`

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/WorkbasketInUseException.java
>  /** Thrown if a specific Workbasket does have content and should be deleted. */
missing `@linkplain`

2021-07-06 09:58 UTC, sofie29 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/WorkbasketNotFoundException.java
>  /** This exception will be thrown if a specific workbasket is not in the database. */
missing `@linkplain`

2021-07-06 09:58 UTC, sofie29 commented on rest/taskana-rest-spring/src/docs/asciidoc/rest-api.adoc
> +| *400 BAD_REQUEST*           | CLASSIFICATION_SERVICE_LEVEL_MALFORMED    |
missing message variables: `serviceLevel`, `classificationKey`, `domain`

2021-07-06 09:58 UTC, sofie29 commented on rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketDefinitionController.java
> +   *     information in workbaskets definitions is incorrect.
capital letter and ' : `Workbaskets'`

2021-07-06 09:58 UTC, sofie29 commented on web/src/app/administration/components/access-items-management/access-items-management.component.ts
> +  } */
delete comment because it is duplicated

2021-07-06 09:58 UTC, sofie29 commented on web/src/app/shared/models/notifications.ts
>  ]);
delete this file

2021-07-06 11:20 UTC, mustaphazorgati reviewed
WIP - Review not done

2021-07-06 11:30 UTC, Tristan2357 requested changes

2021-07-06 11:40 UTC, sofie29 commented on web/src/app/shared/models/notifications.ts
>  export const notifications = new Map<NOTIFICATION_TYPES, Pair<string, string>>([
no, is already deleted

2021-07-06 11:41 UTC, sofie29 commented on web/src/app/shared/components/popup/dialog-pop-up.component.html
> +  <button *ngIf="isDataSpecified" [mat-dialog-close]="callback" mat-raised-button color="primary"> Delete </button>
yes

2021-07-06 12:32 UTC, Tristan2357 commented on web/src/app/shared/models/notifications.ts
>  export const notifications = new Map<NOTIFICATION_TYPES, Pair<string, string>>([
weird, github does not show it as deleted

2021-07-06 14:35 UTC, gitgoodjhe requested changes

2021-07-06 14:35 UTC, gitgoodjhe commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/WorkbasketMarkedForDeletionException.java
> +            "Workbasket '%s' could not be deleted, but was marked for deletion.", workbasketId),
workbasket with id?

2021-07-06 14:35 UTC, gitgoodjhe commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/WorkbasketNotFoundException.java
>    public String getKey() {
missing getter for domain?

2021-07-06 14:35 UTC, gitgoodjhe commented on rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaRestExceptionHandler.java
> +    InvalidOwnerException.class,
Pls make this Bad Request

2021-07-06 14:35 UTC, gitgoodjhe commented on rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaRestExceptionHandler.java
> +    InvalidTaskStateException.class,
Pls make this Bad Request

2021-07-06 14:35 UTC, gitgoodjhe commented on rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaRestExceptionHandler.java
> +    InvalidCallbackStateException.class,
Pls make this Bad Request

2021-07-06 14:35 UTC, gitgoodjhe commented on rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
> +   * <ul>
pls delete

2021-07-06 16:11 UTC, Tristan2357 requested changes

2021-07-06 16:11 UTC, Tristan2357 commented on rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketDefinitionController.java
> +   * @throws WorkbasketNotFoundException if do not exists a Workbasket in the system with the used
```suggestion
   * @throws WorkbasketNotFoundException if do not exists a {@linkplain Workbasket} in the system with the used
```

2021-07-06 16:11 UTC, Tristan2357 commented on rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketDefinitionController.java
> +   *     information in Workbaskets' definitions is incorrect.
```suggestion
   *     information in {@linkplain Workbasket}s' definitions is incorrect.
```

2021-07-06 16:11 UTC, Tristan2357 commented on rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketDefinitionController.java
> +   * @throws ConcurrencyException if Workbasket was updated by an other user
```suggestion
   *     {@linkplain Workbasket} and access id already exists.
   * @throws ConcurrencyException if {@linkplain Workbasket} was updated by another user
```

2021-07-06 16:21 UTC, Tristan2357 requested changes

2021-07-06 16:21 UTC, Tristan2357 commented on lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
> +   * @throws MalformedServiceLevelException if the given service level of the Classification is
```suggestion
   * @throws MalformedServiceLevelException if the given service level of the {@linkplain Classification} is
```

2021-07-06 16:21 UTC, Tristan2357 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketService.java
> +   * @throws ConcurrencyException if an attempt is made to update the Workbasket and another user
```suggestion
   * @throws NotAuthorizedException if the current user is not authorized to update the {@linkplain Workbasket}
   * @throws WorkbasketNotFoundException if the {@linkplain Workbasket} cannot be found.
   * @throws ConcurrencyException if an attempt is made to update the {@linkplain Workbasket} and another user
```

2021-07-06 16:21 UTC, Tristan2357 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketService.java
> +   * @param workbasketId the workbasket id used to identify the referenced Workbasket
```suggestion
   * @param workbasketId the workbasket id used to identify the referenced {@linkplain Workbasket}
```

2021-07-07 06:19 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskanaHistoryEngineImpl.java
> +    configuration.getTypeHandlerRegistry().register(JdbcType.TIMESTAMP, new InstantTypeHandler());
https://github.com/Taskana/taskana/pull/1630

2021-07-07 06:57 UTC, tge20 commented on common/taskana-common/src/main/java/pro/taskana/common/api/exceptions/MismatchedRoleException.java
> +
first sentence

2021-07-07 06:57 UTC, tge20 commented on lib/taskana-core/src/main/java/pro/taskana/task/api/exceptions/MismatchedTaskCommentCreatorException.java
> +
first sentence

2021-07-07 06:57 UTC, tge20 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/MismatchedWorkbasketPermissionException.java
> +
first sentence

2021-07-07 06:57 UTC, tge20 commented on lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/WorkbasketMarkedForDeletionException.java
> + * pro.taskana.workbasket.api.WorkbasketService#deleteWorkbaskets(List)} to indicate whether a
import above

2021-07-07 07:21 UTC, Tristan2357 approved these changes

2021-07-08 12:44 UTC, mustaphazorgati commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/ServiceLevelHandler.java
> +    taskMapper.updateTaskDueDates(existingAndAuthorizedTasks.getLeft(), referenceTask);
if not empty

2021-07-08 12:52 UTC, mustaphazorgati commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/ServiceLevelHandler.java
> +    Pair<List<MinimalTaskSummary>, BulkLog> existingAndAuthorizedTasks =
test dis

2021-07-08 12:52 UTC, mustaphazorgati commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/ServiceLevelHandler.java
> +    Pair<List<MinimalTaskSummary>, BulkLog> existingAndAuthorizedTasks =
and TSI aswell

2021-07-14 08:49 UTC, mustaphazorgati commented
A follow-up PR will be created. That PR will include minor improvements + Tests for the changes in the TaskServiceImpl and ServiceLevelHandler

2021-07-14 08:49 UTC, merged