TSK-1656: Added from and until for created and completed
Taskana/taskana pull request #1627
Opened 2021-07-05 10:51 UTC by Tristan2357

https://sonarcloud.io/dashboard?branch=TSK-1656&id=Tristan2357_taskana

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-07-05 14:15 UTC, holgerhagen requested changes
Could you please add at least one test case for each parameter?

2021-07-06 08:34 UTC, mustaphazorgati commented
> Could you please add at least one test case for each parameter?

We have a dedicated ticket for that: https://taskana.atlassian.net/browse/TSK-1545

No need to do that in this PR.

2021-07-06 09:25 UTC, gitgoodjhe commented
Did you test it manually once with e.g. Postman?

2021-07-07 14:46 UTC, holgerhagen approved these changes

2021-07-07 20:08 UTC, merged