TSK-1658: Add notIn-filter for the TaskQuery
Taskana/taskana pull request #1635
Opened 2021-07-14 07:17 UTC by Tristan2357

Adapted the TaskQueryMapper
Adapted the TaskQuery
Expanded the (Rest) API

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-07-14 07:18 UTC, Tristan2357 commented
https://sonarcloud.io/dashboard?branch=TSK-1658&id=Tristan2357_taskana 
-> Fails, because i do not know how to properly test the Db2 versions of the queries. 
Also the about 30 Code Smells are all because of duplication of literal Strings, which i did not fix, because it would decrease the readability.

2021-07-14 13:05 UTC, mustaphazorgati requested changes

2021-07-14 13:05 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/ArchitectureTest.java
> +          if (sqlStrings.isEmpty()
this "breaks" the architechture test. Let's have a look how we can fix that ;)

2021-07-14 13:05 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/objectreference/QueryObjectReferencesWithPaginationAccTest.java
>    }
delete

2021-07-14 13:05 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
> +  void should_ReturnCorrectResults_When_QueryingForDescriptionAndPriority() {
split tests :)

2021-07-15 11:33 UTC, mustaphazorgati approved these changes

2021-07-15 11:33 UTC, mustaphazorgati commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
> +        + "</if> "
let's extract this to a method. A `checkForAuthorization` is more readable than this :)

2021-07-15 11:33 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
> +  void should_ReturnCorrectResults_When_QueryingForDescriptionAndPriority() {
still not split :)

2021-07-15 11:33 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
> +            Pair.of(TaskCustomField.CUSTOM_16, new String[] {"custom16"}));
Well done! 
I am aware that each result has only two hits. But I prefer a Triplet where the expected amount is viewable here.

Reason: If for some reason some test data gets added the number's will not match anymore

2021-07-15 12:03 UTC, merged