TSK-1659
Taskana/taskana pull request #1636
Opened 2021-07-16 13:43 UTC by tge20

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-07-16 14:26 UTC, tge20 commented on lib/taskana-core/src/test/java/acceptance/report/ProvideClassificationReportAccTest.java
> +            .customAttributeLike(TaskCustomField.CUSTOM_1, "Geschaeftsstelle A")
```suggestion
            .customAttributeLike(TaskCustomField.CUSTOM_1, "%eftsstelle A")
```

2021-07-20 09:24 UTC, holgerhagen requested changes
aren't the "custom-X-not-in" filter missing?

2021-08-02 14:07 UTC, holgerhagen requested changes

2021-08-02 14:07 UTC, holgerhagen commented on rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/MonitorControllerIntTest.java
> +    // TODO: FINISH THIS TEST
What does this mean?

2021-08-02 19:23 UTC, merged