TSK-1630,TSK-1669,TSK-1670: Refactored Type-Ahead component
Taskana/taskana pull request #1675
Opened 2021-08-17 12:14 UTC by sofie29

Commits will be squashed after review. Is the comma separation in the commit message correct?

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-08-20 12:38 UTC, cnguyen-de requested changes
When inputting a valid access Id and then making the input invalid, the valid access Id (not the actual invalid value) is sent to backend

2021-08-23 08:20 UTC, sofie29 commented
The last commit removed the changes for TSK-1669. Due to time issues, I prefer to postpone working on TSK-1669.

2021-08-26 09:58 UTC, cnguyen-de submitted a review, later dismissed
Not sure if there is a way to quickly fix 1669, but we can do it with another PR if this one is needed immediately

2021-09-01 08:53 UTC, cnguyen-de approved these changes

2021-09-01 08:54 UTC, merged