TSK-1710: Fixed a few code smells
Taskana/taskana pull request #1684
Opened 2021-08-24 12:24 UTC by LiaLissmann

https://sonarcloud.io/dashboard?branch=TSK-1710&id=LiaLissmann_taskana
---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-08-24 12:32 UTC, mustaphazorgati requested changes

2021-08-24 12:32 UTC, mustaphazorgati commented on common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java
> -    runner.setErrorLogWriter(new PrintWriter(errorWriter));
please use `errorLogWriter`

2021-08-24 12:32 UTC, mustaphazorgati commented on common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java
remove that `toString()` in line 81

2021-08-24 12:32 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskHistoryQueryImpl.java
> -  private TaskHistoryQueryColumnName columnName;
reset

2021-08-24 12:32 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskHistoryQueryImpl.java
> -    this.addOrderCriteria(columnName.toString(), sortDirection);
reset

2021-08-24 12:32 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskHistoryQueryImpl.java
annotate with `@SupressWarnings("unused");`

2021-08-24 12:32 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/WorkbasketHistoryQueryImpl.java
> -  private WorkbasketHistoryQueryColumnName columnName;
reset

2021-08-24 12:32 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/WorkbasketHistoryQueryImpl.java
> -    this.addOrderCriteria(columnName.toString(), sortDirection);
reset

2021-08-24 12:32 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/WorkbasketHistoryQueryImpl.java
> -  private WorkbasketHistoryQueryColumnName columnName;
annotate with @SupressWarnings("unused");?

2021-08-24 12:32 UTC, mustaphazorgati commented on history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/WorkbasketHistoryQueryImpl.java
> -      this.columnName = null;
reset

2021-08-24 13:14 UTC, benjamineckstein approved these changes

2021-08-25 08:13 UTC, mustaphazorgati approved these changes

2021-08-25 08:13 UTC, merged