TSK-1715: Implemented OwnerNotIn-Filter for TaskQuery.
Taskana/taskana pull request #1686
Opened 2021-08-24 16:10 UTC by martisaw

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-08-24 16:24 UTC, martisaw commented
https://sonarcloud.io/dashboard?branch=tsk-1715&id=martisaw_taskana

2021-08-30 11:45 UTC, gitgoodjhe requested changes

2021-08-30 11:45 UTC, gitgoodjhe commented on lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
> +   * Filter out owners.
In the other java doc for the api we usually also added "This is an exact match". Also we always added "of the task". Could you change this to "Filter out owners of the task. This is an exact match."?

2021-08-31 07:07 UTC, gitgoodjhe approved these changes

2021-08-31 11:00 UTC, merged