TSK-1690: removed toString() methods from Exceptions to prevent unspe…
Taskana/taskana pull request #1722
Opened 2021-09-29 13:22 UTC by martisaw

…cific error messages

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [x] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-09-29 13:22 UTC, martisaw commented
https://sonarcloud.io/dashboard?branch=tsk-1690&id=martisaw_taskana

2021-09-29 21:39 UTC, mustaphazorgati requested changes

2021-09-29 21:39 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/ArchitectureTest.java
> +            .haveSimpleNameNotStartingWith("Taskana")
please use  `doNotBelongToAnyOf`

2021-09-29 21:39 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/ArchitectureTest.java
> +            .notImplement("toString()");
This does not work, because `notImplement` requires a class, not a method. You have to create your own ArchCondition

2021-09-29 21:39 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/ArchitectureTest.java
> +  void exceptionsShouldNotHaveToStringMethod() {
I also expect a rule which checks, that TaskanaException and TaskanaRuntimeException contain a `toString` method

2021-10-05 12:22 UTC, mustaphazorgati approved these changes

2021-10-05 12:27 UTC, merged