Tsk1764: Filter for PriorityReport
Taskana/taskana pull request #1754
Opened 2021-11-03 12:28 UTC by holgerhagen

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [x] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [x] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2021-11-03 12:28 UTC, holgerhagen commented
https://sonarcloud.io/summary/new_code?branch=tsk1764&id=holgerhagen_taskana

Failed, but we agreed that it is ok.

2021-11-03 13:13 UTC, gitgoodjhe requested changes

2021-11-03 13:13 UTC, gitgoodjhe commented on rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/MonitorControllerRestDocTest.java
> +        .perform(get(RestEndpoints.URL_MONITOR_TASK_STATUS_REPORT + "?state=READY"))
Why did you add the state filter here?

2021-11-04 08:19 UTC, gitgoodjhe approved these changes

2021-11-04 09:41 UTC, merged