TSK-1665: object-reference can be used as parameter in a task query.
Taskana/taskana pull request #1793
Opened 2022-01-04 16:25 UTC by ryzheboka

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2022-01-05 09:50 UTC, holgerhagen requested changes
Have you actually verified the results of your test? To be honest I'm not sure if the object reference query is working at all at the moment. Therefore I would like to make sure that we do not implement a test on invalid data.

There is nothing wrong in this PR. I just don't see the link to the test data you are using.

2022-01-05 10:57 UTC, mustaphazorgati commented on rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
> +            + "%7B%22systemInstance%22%3A%22MyInstance1%22%2C%22type%22%3A%22MyType1%22%7D";
Please use `UrlEncode.encode()`, so that the object is human readable :)

2022-01-12 13:58 UTC, gitgoodjhe requested changes

2022-01-12 13:58 UTC, gitgoodjhe commented on pom.xml
> -    <version.checkstyle>9.2</version.checkstyle>
Why do we have this dependency update here?

2022-01-12 13:58 UTC, gitgoodjhe commented on .github/workflows/continuous-integration.yml
> +        uses: actions/setup-node@v2.5.1
Why did this change in this PR?

2022-01-12 13:58 UTC, gitgoodjhe commented on rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
> +  void testGetAllTasksByPrimaryObjectReference() throws UnsupportedEncodingException {
This does not fullfill our coding guidelines. Reference here: https://taskana.atlassian.net/wiki/spaces/TAS/pages/2634055697/Testing+Guidelines

2022-01-12 15:30 UTC, gitgoodjhe commented
> Please fix your commits. For some reason this PR contains 2 dependabot commits

see comments above :P

2022-01-13 14:43 UTC, gitgoodjhe approved these changes

2022-01-15 10:54 UTC, mustaphazorgati approved these changes

2022-01-15 10:54 UTC, mustaphazorgati commented
@holgerhagen we still need your approval before merging this PR :)

2022-01-17 07:41 UTC, holgerhagen approved these changes

2022-01-17 07:42 UTC, merged