TSK-1852: refactor JavaDoc in TaskService
Taskana/taskana pull request #1919
Opened 2022-04-25 11:05 UTC by ryzheboka

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2022-05-09 15:12 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
> +   * @return the updated unclaimed {@linkplain Task}
the unclaimed Task sounds better to me

2022-05-09 15:14 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
> +   * @throws InvalidStateException if the {@linkplain Task} with taskId wasn't claimed before
Ok :)

2022-05-09 16:23 UTC, mustaphazorgati requested changes

2022-05-09 16:23 UTC, mustaphazorgati commented on lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
> +   *     TaskState#CLAIMED} nor {@linkplain TaskState#COMPLETED}
```suggestion
   * @throws InvalidStateException if the {@linkplain Task} with taskId is neither {@linkplain
   *     TaskState#CLAIMED} nor {@linkplain TaskState#COMPLETED}
```

2022-05-31 11:23 UTC, mustaphazorgati approved these changes

2022-05-31 14:01 UTC, merged