TSK-1865: Reorder methods in ClassificationService
Taskana/taskana pull request #1931
Opened 2022-05-14 14:26 UTC by ensarevlideveloper

New ordering follows CRUD principles for better readability.
---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [X] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [X] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [X] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2022-05-14 14:26 UTC, ensarevlideveloper commented
_bump_

2022-05-28 09:48 UTC, mustaphazorgati requested changes
The order of the overloaded method's is not consistent (especially not with the already reordered WorkbasketService).

Please use first the methods, which use the technical id, then the method using key + domain

2022-05-28 09:48 UTC, mustaphazorgati commented on lib/taskana-core/src/main/java/pro/taskana/classification/api/ClassificationService.java
> +  // READ
space missing below

2022-05-28 09:48 UTC, mustaphazorgati commented on lib/taskana-core/src/main/java/pro/taskana/classification/api/ClassificationService.java
> +  // DELETE
space missing below

2022-05-30 09:54 UTC, mustaphazorgati approved these changes

2022-05-31 10:14 UTC, merged