TSK-1914: introduce IN_REVIEW and READY_FOR_REVIEW Task status
Taskana/taskana pull request #1966
Opened 2022-07-13 15:53 UTC by ryzheboka

---
Release Notes:

```
TSK-1914: introduce IN_REVIEW and READY_FOR_REVIEW Task status. Extend claim, cancelClaim and complete accordingly.
```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [x] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2022-07-18 07:18 UTC, mustaphazorgati requested changes
All in all this looks very nice! :rocket: 
more important: This does not break the existing functionality when users don't want to use the review feature.

General remarks:
* Please remove the diff from the archunit store files, since the architecture tests are currently disabled
* I did not manually verify that all number changes match with your newly created tasks. I trust you on this one.
* Question: Did you mirror all claim / cancel claim tasks? I've seen a mirror on most test, but did not verify that you've mirrored all tests.
* Question: Should we, like SonarCloud suggests, use TestFactories to merge those tests? Lets talk about this. I am personally not sure.
* Question: Why didn't you use the test api for the newly created tests? Do you think it still makes sense to migrate the new tests to the test api? Again, let's talk about this :)

2022-07-18 07:18 UTC, mustaphazorgati commented on lib/taskana-core/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +  void should_forceCompleteTask_When_InReviewByAnotherUser() throws Exception {
```suggestion
  void should_ForceCompleteTask_When_InReviewByAnotherUser() throws Exception {
```

2022-07-19 09:46 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
> +        || task.getState().equals(TaskState.IN_REVIEW)) {
Looks good :)

2022-07-19 09:51 UTC, ryzheboka commented on lib/taskana-core/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +  void should_forceCompleteTask_When_InReviewByAnotherUser() throws Exception {
Ok

2022-07-19 09:51 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
> +    if (task.getState().equals(TaskState.IN_REVIEW)) {
Ok

2022-07-19 13:10 UTC, mustaphazorgati approved these changes

2022-07-19 13:27 UTC, merged