TSK-1984 Refactor TaskCommentAccTests to use Test-API
Taskana/taskana pull request #2076
Opened 2023-02-01 06:50 UTC by arolfes

[Sonar](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1984-refactor-TaskCommentAccTests)

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2023-10-31 11:07 UTC, jamesrdi requested changes

2023-10-31 11:07 UTC, jamesrdi commented on lib/taskana-core-test/src/test/java/acceptance/taskcomment/delete/DeleteTaskCommentAccTest.java
> +        .workbasketId(defaultWorkbasket.getId())
Add new WorkbasketPermission.READTASKS permission here

2023-10-31 11:07 UTC, jamesrdi commented on lib/taskana-core-test/src/test/java/acceptance/taskcomment/delete/DeleteTaskCommentAccTest.java
> +    assertThatThrownBy(() -> taskService.deleteTaskComment(comment1.getId()))
Thrown Exception should be NotAuthorizedOnTaskCommentException, and follow the testing guideline of Exception

2023-10-31 11:07 UTC, jamesrdi commented on lib/taskana-core-test/src/test/java/acceptance/taskcomment/delete/DeleteTaskCommentAccTest.java
> +  void should_DeleteTaskComment_When_NoExplicitPermissionsButUserIsInAdministrativeRole()
This test seems similar to the should_DeleteTaskComment_When_UserIsInAdministrativeRole

2023-10-31 11:07 UTC, jamesrdi commented on lib/taskana-core-test/src/test/java/acceptance/taskcomment/delete/DeleteTaskCommentAccTest.java
> +  void should_FailToDeleteTaskComment_When_TaskCommentIsNotExisting() throws Exception {
Follow the testing guideline

2023-10-31 11:07 UTC, jamesrdi commented on lib/taskana-core-test/src/test/java/acceptance/taskcomment/query/QueryTaskCommentAccTest.java
> +        .workbasketId(defaultWorkbasket.getId())
Add the new WorkbasketPermission.READTASKS permission

2023-10-31 11:07 UTC, jamesrdi commented on lib/taskana-core-test/src/test/java/acceptance/taskcomment/query/QueryTaskCommentAccTest.java
> +          () -> taskService.createTaskCommentQuery().taskIdIn(task1.getId()).list();
Follow testing guideline, check also if fields are set correctly

2023-10-31 11:07 UTC, jamesrdi commented on lib/taskana-core-test/src/test/java/acceptance/taskcomment/query/QueryTaskCommentAccTest.java
> +      implements TaskanaEngineConfigurationModifier {
TaskanaEngineConfigurationModifier has been deprecated and changed to TaskanaConfigurationModifier

2023-10-31 11:07 UTC, jamesrdi commented on lib/taskana-core-test/src/test/java/acceptance/taskcomment/query/QueryTaskCommentAccTest.java
> +    public void modify(TaskanaEngineConfiguration taskanaEngineConfiguration) {
TaskanaEngineConfiguration has been deprecated, use TaskanaConfiguration.Builder instead

2023-10-31 11:10 UTC, jamesrdi requested changes
Please rebase this PR

2023-10-31 17:37 UTC, arolfes commented
Hello @jamesrdi ,
Thank you for reviewing this old PR.
Unfortunately, I don't have time at the moment to implement the changes you've rightly suggested.

If you have more time, please throw the PR away and start from scratch. Knowing my current workload, I won't be able to do it until at least Christmas.

Best Regards Alex

2023-11-02 13:46 UTC, jamesrdi commented
Ok @arolfes I will take care of this PR :)

2023-11-07 09:23 UTC, arolfes commented
> Ok @arolfes I will take care of this PR :)

Thank you, I close this PR now

2023-11-07 09:23 UTC, closed without merging