TSK-2202: ClaimTaskAccTest refactored to use test-api
Taskana/taskana pull request #2204
Opened 2023-03-30 10:50 UTC by jamesrdi

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2023-03-30 11:01 UTC, arolfes commented
Hi @jamesrdi ,

thank you very much for your contribution. I will have a closer look in the next couple of days.

can you remove the yarn.lock file from your commit and maybe add it to `.gitignore`

please change your commit message to:

`Closes #2204 - ClaimTaskAccTest refactored to use test-api`

2023-03-30 12:00 UTC, ryzheboka requested changes

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    assertThat(task.getState()).isSameAs(TaskState.CLAIMED);
You don't need this assertion, because you set the state in the lines above. Could you remove it?

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    assertThat(task.getState()).isSameAs(TaskState.IN_REVIEW);
You don't need this assertion, because you set the state in the lines above. Could you remove it?

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    ThrowingCallable call = () -> taskService.claim(task.getId());
Please add a newline after this line according to the given when then rule

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    ThrowingCallable call = () -> taskService.claim(task.getId());
Please add a newline after this line according to the given when then rule

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    ThrowingCallable call = () -> taskService.claim(task.getId());
Please add a newline after this line according to the given when then rule

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    ThrowingCallable call = () -> taskService.claim(task.getId());
Please add a newline after this line according to the given when then rule

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    Task unclaimedTask = taskService.cancelClaim(claimedTask.getId());
Please add a newline after this line according to the given when then rule

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    Task unclaimedTask = taskService.cancelClaim(claimedTask.getId());
Please add a newline after this line according to the given when then rule

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    ThrowingCallable call = () -> taskService.cancelClaim(claimedTask.getId());
Please add a newline after this line according to the given when then rule

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    ThrowingCallable call = () -> taskService.cancelClaim(claimedTask.getId());
Please add a newline after this line according to the given when then rule

2023-03-30 12:00 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
> +    Task unclaimedTask = taskService.forceCancelClaim(claimedTask.getId());
Please add a newline after this line according to the given when then rule

2023-03-31 06:15 UTC, ryzheboka requested changes

2023-03-31 07:01 UTC, ryzheboka commented
Hi @arolfes,
did you mean: `Closes #2202 - ClaimTaskAccTest refactored to use test-api` ?
#2204 is the number of the PR, while #2202 is the number of the issue that will be closed by the PR.

2023-03-31 07:47 UTC, arolfes commented
> 



> Hi @arolfes, did you mean: `Closes #2202 - ClaimTaskAccTest refactored to use test-api` ? #2204 is the number of the PR, while #2202 is the number of the issue that will be closed by the PR.

yes exactly. Whenn you start the commit message with `Closes #RealNumberOfTheIssue' github will automatically close the issue when the PR is merged

2023-03-31 11:50 UTC, jamesrdi commented on .gitignore
> +db.tar.gz
Okay, I have returned it to how it was

2023-04-05 06:46 UTC, ryzheboka commented
Hi @mustaphazorgati, could you please approve this PR or request additional changes? Your suggested changes have already been addressed :)

2023-04-05 06:47 UTC, mustaphazorgati approved these changes

2023-04-05 07:05 UTC, ryzheboka approved these changes

2023-04-05 07:05 UTC, merged