Closes #2131 Upgrade to java 17
Taskana/taskana pull request #2213
Opened 2023-04-05 09:15 UTC by arolfes

---
Release Notes:

```
#2131 Java 17 Migration
```

 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2023-04-15 17:18 UTC, norman-schmidt requested changes

2023-04-15 17:22 UTC, norman-schmidt commented
some extra review credits for the bash-magician: @cubernetes :D

2023-04-17 06:25 UTC, arolfes commented
> some extra review credits for the bash-magician: @cubernetes :D

Hi @norman-schmidt, @cubernetes,

thank you for reviewing the maven-wrapper scripts. I just used the original one from https://github.com/apache/maven-wrapper . When we want changes in these script file, we should discuss it with the maven-wrapper developers.

Is it ok for you when we not change the `mvnw` scirpt?

2023-04-17 06:53 UTC, norman-schmidt approved these changes

2023-04-17 06:53 UTC, merged