Closes #2295 - Implement EDITTASKS Permission
Taskana/taskana pull request #2301
Opened 2023-06-22 07:31 UTC by jamesrdi

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → (Closes) #<Issue Number>: Your commit message. i.e. Closes #2271: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2023-06-22 13:30 UTC, ryzheboka requested changes
Great work :tada: Could you add a link to Sonarcloud?

2023-06-23 07:42 UTC, ryzheboka commented
Please rebase so that you have only one commit :)

2023-06-23 09:52 UTC, ryzheboka requested changes

2023-06-23 09:52 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
> +    // because of missing permission
We don't need this comment anymore after the change in logic

2023-06-23 09:52 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
> +        WorkbasketSummary workbasket =
Why don't you use checkEditTasksPerm here?

2023-06-23 09:52 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
> +                    WorkbasketPermission.READTASKS, WorkbasketPermission.EDITTASKS)
Why don't you use checkEditTasksPerm here?

2023-06-27 08:12 UTC, ryzheboka commented on lib/taskana-core-test/src/test/java/acceptance/workbasket/get/GetWorkbasketAccTest.java
> +    assertThat(permissions)
Please change assertion to "containsExactlyInAnyOrder". You don't need to check the size.

2023-06-28 12:39 UTC, holgerhagen requested changes

2023-06-29 12:03 UTC, gitgoodjhe approved these changes

2023-06-29 12:10 UTC, ryzheboka approved these changes

2023-06-30 08:01 UTC, holgerhagen requested changes

2023-06-30 08:01 UTC, holgerhagen commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
> +      if (!checkEditTasksPerm(task)) {
Isn't this already checked in "checkPreconditions"?

2023-06-30 08:59 UTC, holgerhagen approved these changes

2023-06-30 09:00 UTC, merged