Closes #2599 - add locking to Query to enable adapter clustering
Taskana/taskana pull request #2629
Opened 2024-07-30 12:53 UTC by ryzheboka

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → (Closes) #&lt;Issue Number&gt;: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2024-08-06 13:03 UTC, gitgoodjhe requested changes

2024-08-06 13:03 UTC, gitgoodjhe commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
> +    this.lockResults = 0;
I don't know if we maybe can solve this differently. For now we can keep it like this but we should look into this once we have more time again.

2024-08-07 10:52 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
> +        + "FETCH FIRST ${lockResults} ROWS ONLY FOR UPDATE "
Should we even allow to use them simultaneously? It doesn't make sense to me, because select and claim already returns one task and locks it

2024-08-07 10:52 UTC, ryzheboka commented on lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
> +   * This method locks the returned rows until the end of the transaction using for update.
That sounds good!

2024-08-07 14:29 UTC, gitgoodjhe approved these changes

2024-08-07 14:29 UTC, merged