Closes #2608: Remove SpringRestDocs as it has been replaced with OpenAPI
Taskana/taskana pull request #2641
Opened 2024-08-06 14:02 UTC by jamesrdi

### Thanks for your PR! Please fill out the following list :)

---
- [ ] I put the ticket or multiple tickets in review
- [ ] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [ ] Sonarcloud link : \<add the link here>
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

2024-08-06 14:03 UTC, jamesrdi commented
Should wait until #2622 is merged

2024-08-06 16:04 UTC, holgerhagen requested changes

2024-08-06 16:04 UTC, holgerhagen commented on rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/models/WorkbasketSummaryRepresentationModel.java
>    /** Identifier to tell if this workbasket can be deleted. */
this line needs to be deleted as well?

2024-08-07 10:14 UTC, jamesrdi commented on rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/models/WorkbasketSummaryRepresentationModel.java
>    /** Identifier to tell if this workbasket can be deleted. */
Yes you are right, I will delete it

2024-08-07 10:16 UTC, jamesrdi commented on history/taskana-simplehistory-rest-spring/src/main/java/pro/taskana/simplehistory/rest/TaskHistoryQueryFilterParameter.java
> -   * Filter by the event type of the Task History Event. This results in a substring search.. (% is
This information is copied as OpenAPI annotation in #2622, that is why I have to wait until #2622 is merged, then I will rebase it

2024-08-07 12:05 UTC, closed without merging